extends:
  - eslint:recommended
  - prettier

plugins:
  - prettier

parserOptions:
  sourceType: module

env:
  es6: true
  node: true

globals:
  danger: true
  message: true
  warn: true
  fail: true
  pr: true
